// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/.well-known/jwks.json": {
            "get": {
                "description": "Returns the active and archived public signing keys for asymmetric Ed25519 token verification without disclosing private key material.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get public JSON Web Key Set (JWKS)",
                "responses": {
                    "200": {
                        "description": "Public JWKS key set",
                        "schema": {
                            "$ref": "#/definitions/token.JWKS"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns 200 OK if the HTTP service process is running and not deadlocked.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "probes"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "Process is healthy",
                        "schema": {
                            "$ref": "#/definitions/http.healthResponse"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Returns 200 OK if the service and database are ready to accept traffic.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "probes"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "Service and database are ready",
                        "schema": {
                            "$ref": "#/definitions/http.healthResponse"
                        }
                    },
                    "503": {
                        "description": "Database connection ping failed or timed out",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/login": {
            "post": {
                "description": "Authenticates email and password, creates a persistent session, and returns a signed Ed25519 access JWT.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate user and issue access JWT",
                "parameters": [
                    {
                        "description": "User credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Authentication successful",
                        "schema": {
                            "$ref": "#/definitions/http.loginResponse"
                        }
                    },
                    "400": {
                        "description": "Malformed JSON or excessive payload",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid email or password",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "413": {
                        "description": "Payload too large (\u003e 4 KiB)",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported media type",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded (too many login attempts)",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Database unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout": {
            "post": {
                "description": "Revokes the active session via either Authorization Bearer header or application/json refresh_token body. Providing both credentials simultaneously returns 400.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log out current session",
                "parameters": [
                    {
                        "description": "Refresh token body (used when logging out without access token)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/http.logoutRefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Session successfully revoked"
                    },
                    "400": {
                        "description": "Ambiguous credentials (both Bearer and body) or malformed JSON",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized or invalid/expired credentials",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "413": {
                        "description": "Payload too large (\u003e 4 KiB)",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported media type",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Database unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves the authenticated account information using verified token claims and persisted active session state.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get current user profile",
                "responses": {
                    "200": {
                        "description": "Account profile details",
                        "schema": {
                            "$ref": "#/definitions/http.meResponseEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized or session revoked/expired",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Database unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/refresh": {
            "post": {
                "description": "Rotates a valid unconsumed refresh token, invalidates the old token, and issues a new access JWT and successor refresh token. If a previously consumed token is replayed, the session family is immediately revoked.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Rotate refresh token and issue new access JWT",
                "parameters": [
                    {
                        "description": "Refresh token payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.refreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Rotation successful",
                        "schema": {
                            "$ref": "#/definitions/http.refreshResponse"
                        }
                    },
                    "400": {
                        "description": "Malformed JSON or missing refresh_token",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid, expired, revoked, or replayed credentials",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "413": {
                        "description": "Payload too large (\u003e 4 KiB)",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported media type",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Database unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/register": {
            "post": {
                "description": "Creates a new registered account with an Argon2id password hash. Body is limited to 4 KiB and unknown fields are rejected.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new account",
                "parameters": [
                    {
                        "description": "Registration credentials (email and password)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Account created successfully",
                        "schema": {
                            "$ref": "#/definitions/http.registerResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON body, email format, or password length",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Account with this canonical email already exists",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "413": {
                        "description": "Request body exceeds limit",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "415": {
                        "description": "Content-Type must be application/json",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service temporarily unavailable, please retry",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.accountResponse": {
            "type": "object",
            "required": [
                "created_at",
                "email",
                "email_verified",
                "id",
                "status"
            ],
            "properties": {
                "created_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-10-04T00:00:00Z"
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user@example.com"
                },
                "email_verified": {
                    "type": "boolean",
                    "example": false
                },
                "id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                }
            }
        },
        "http.errorDetail": {
            "type": "object",
            "required": [
                "code",
                "message",
                "request_id"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "invalid_request"
                },
                "message": {
                    "type": "string",
                    "example": "Invalid email or password"
                },
                "request_id": {
                    "type": "string",
                    "example": "c6b8f3a1-4d2e-4f7b-9c1a-2e5f8a9b0c1d"
                }
            }
        },
        "http.errorResponse": {
            "type": "object",
            "required": [
                "error"
            ],
            "properties": {
                "error": {
                    "$ref": "#/definitions/http.errorDetail"
                }
            }
        },
        "http.healthResponse": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "http.loginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "format": "email",
                    "maxLength": 254,
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1,
                    "example": "ExamplePassword123"
                }
            }
        },
        "http.loginResponse": {
            "type": "object",
            "required": [
                "access_token",
                "account",
                "expires_in",
                "refresh_expires_in",
                "refresh_token",
                "token_type"
            ],
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJFZERTQSI..."
                },
                "account": {
                    "$ref": "#/definitions/http.accountResponse"
                },
                "expires_in": {
                    "type": "integer",
                    "example": 600
                },
                "refresh_expires_in": {
                    "type": "integer",
                    "example": 2592000
                },
                "refresh_token": {
                    "type": "string",
                    "example": "u4W78Q9jKl_..."
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "http.logoutRefreshRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "u4W78Q9jKl_..."
                }
            }
        },
        "http.meResponseEnvelope": {
            "type": "object",
            "properties": {
                "account": {
                    "$ref": "#/definitions/http.accountResponse"
                }
            }
        },
        "http.refreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "u4W78Q9jKl_..."
                }
            }
        },
        "http.refreshResponse": {
            "type": "object",
            "required": [
                "access_token",
                "expires_in",
                "refresh_expires_in",
                "refresh_token",
                "token_type"
            ],
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJFZERTQSI..."
                },
                "expires_in": {
                    "type": "integer",
                    "example": 600
                },
                "refresh_expires_in": {
                    "type": "integer",
                    "example": 2592000
                },
                "refresh_token": {
                    "type": "string",
                    "example": "x8K23P9mLz_..."
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "http.registerRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "format": "email",
                    "maxLength": 254,
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 8,
                    "example": "securePassword123!"
                }
            }
        },
        "http.registerResponse": {
            "type": "object",
            "required": [
                "account"
            ],
            "properties": {
                "account": {
                    "$ref": "#/definitions/http.accountResponse"
                }
            }
        },
        "token.JWK": {
            "type": "object",
            "properties": {
                "crv": {
                    "type": "string"
                },
                "kid": {
                    "type": "string"
                },
                "kty": {
                    "type": "string"
                },
                "use": {
                    "type": "string"
                },
                "x": {
                    "type": "string"
                }
            }
        },
        "token.JWKS": {
            "type": "object",
            "properties": {
                "keys": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/token.JWK"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and the access JWT.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.2.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Gatekeeper Auth Service API",
	Description:      "Authentication service for Gatekeeper.\nImplements AUTH-01 registration and AUTH-02 authentication (login, access JWT, sessions, profile, logout, JWKS).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
